### ISSUE TITLE
The multichannel pipeline parses at some cases the "scene#X_sm' thumbnail instead of the Image_label_sm 

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#362] opened 2023-10-18 17:30 UTC
It appears that the API is parsing black images. In the file system, there are multiple thumbnails available, but the correct one to use is 'Label_image_sm,' as shown in the example below for 2023_03_10_P2_S7_FL:
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/b3216214-db88-46a8-a4a4-4c54d691bc60)
file path: \\ai-fas12.niaid.nih.gov\RMLSOHedwigQA\Assets\LID\jecohen\maximovao-2023-1011-Dans_Keyword_10112023\RNA-2023-1012-Dans_Project_Experiment_Tag_10112023_C-PipelineProcessingtest\HQ_Images\2023_03_10_P2_S7_FL
Upon examining the JPEG images in the file system, it appears that what was parsed to the UI was 'Scene#0_sm.'
page:
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/f8b3b032-f261-4e20-83f5-540f8a4d69b2)
The "black" images are the wrong thumbnails.

**Comment by philipmac** [comment] 2023-10-19 14:55
@NetaFG  please update with current run from dev.

**Comment by NetaFG** [comment] 2023-10-20 14:26
Tested in Dev on 10/18/2023
See the secreenshot before the fix (Dev):
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/887acdb9-ede3-498d-8d29-10d34e03c663)

Test pipeline run: (Dev)  https://prefect1.hedwig-workflow-api.niaiddev.net/default/flow-run/0983cfa5-33ca-42e8-bfa0-6880ae2135f9
Results(Dev):
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/627bd399-1e12-4b2f-b860-c2d4aacb9a6b)
 Hedwig UI(Dev):
https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjozNTY5/records 
Dev Test = PASS

The fix was prometed to QA on 10/19/2023
Pipeline run (QA):
https://prefect1.hedwig-workflow-api.niaidqa.net/default/flow-run/5d536148-d099-427d-8908-75cc6c63363c
Hedwig UI URL(QA):
https://hedwig2qa.niaid.nih.gov/sessions/U2Vzc2lvbjozMjky/records#N4IgSgpgxg9gTgEwDIEsDOAXFA7A5iALlADUBRMAZQEkB5AOUIEYAaEYgQSQFVTDQ0IAQzhQAFhQxwc+AiBCsADsIjYMFQQFsFAGwgAxFNowQ4hANoguAJj0YoAcQAe2mgCsA1gAY6AFSoBeEABdVmUDIxM0ClEYAHdsQkkAVwgAX3SgA===
Results (QA):
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/ccdbf455-bde0-42e8-9e40-546d4fde932d)

**Comment by philipmac** [comment] 2023-10-20 14:57
@NetaFG  - if you feel the issue is resolved in please open with this statement, and close issue if it's been resolved.

**Closed** 2023-11-09 20:52 UTC
